package com.gianghv.uniqlo.theme

import androidx.compose.ui.graphics.Color

// generated by https://m3.material.io/theme-builder#/custom
// Color palette was taken here: https://colorhunt.co/palettes/popular

internal val md_theme_light_primary = Color(0xffed1b24)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0x80ed1b24)
internal val md_theme_light_onPrimaryContainer = Color(0xFFFFFFFF)

internal val md_theme_light_secondary = Color(0xffff2a1a)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0x80ed1b24)
internal val md_theme_light_onSecondaryContainer = Color(0xffffffff)

internal val md_theme_light_tertiary = Color(0xFF808080)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFF808080)
internal val md_theme_light_onTertiaryContainer = Color(0xFFFFFFFF)

internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)

internal val md_theme_light_background = Color(0xffffffff)
internal val md_theme_light_onBackground = Color(0xFF919191)

internal val md_theme_light_surface = Color(0xffffffff)
internal val md_theme_light_onSurface = Color(0xff000000)
internal val md_theme_light_surfaceContainer = Color(0xfff3f3f3)
internal val md_theme_light_onSurfaceContainer = Color(0xffffffff)

internal val md_theme_light_surfaceVariant = Color(0xFFDBE4E7)
internal val md_theme_light_onSurfaceVariant = Color(0xFF3F484B)

internal val md_theme_light_outline = Color(0xFFE3E3E3)
internal val md_theme_light_inverseOnSurface = Color(0xFFFFF0C0)
internal val md_theme_light_inverseSurface = Color(0xFF3A3000)
internal val md_theme_light_inversePrimary = Color(0xFF55D6F4)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF00687A)
internal val md_theme_light_outlineVariant = Color(0xFFBFC8CB)
internal val md_theme_light_scrim = Color(0xFF000000)

val Black = Color(0xff000000)
val White = Color(0xffffffff)
val Black_28 = Color(0xFF262628)
val Black_34 = Color(0xFF110034)
val Black_22 = Color(0xFF222222)
val Black_10 = Color(0xFF101010)
val Black_alpha_8 = Color(0, 0, 0, 21)
val Black_alpha_60 = Color(0x99000000)
val Yellow = Color(0xFFFFD700)
val Yellow_alpha_0 = Color(245, 216, 55, 0)
val Yellow_alpha_39 = Color(255, 215, 0, 99)
val Silver = Color(0xFFD9D9D9)
val Silver_d8 = Color(0xFFD3D1D8)
val Orange = Color(0xFFDF3448)
val Orange_alpha_5 = Color(0x0DE54F4C)
val Orange_alpha_12 = Color(0x1FDF3448)
val Orange_alpha_50 = Color(0x80E54F4C)
val Orange_51 = Color(0xFFF28551)
val Orange_55 = Color(0xFFF9A455)
val Red_48 = Color(0xFFDE3048)
val Alabaster = Color(0xFFF1E9E9)

val Gray = Color(0xFFEAE6E6)
